-- The commands below were used in MySQL Worbench 8.0

-- Inserting values into OLAP dimension tables

insert into escopo values
(1, (select descricao_escopo from escopo_oltp where cod_escopo = 1)),
(2, (select descricao_escopo from escopo_oltp where cod_escopo = 2));

insert into prioridade values
(1, (select descricao_prioridade from prioridade_oltp where cod_prioridade = 1)),
(2, (select descricao_prioridade from prioridade_oltp where cod_prioridade = 2)),
(3, (select descricao_prioridade from prioridade_oltp where cod_prioridade = 3)),
(4, (select descricao_prioridade from prioridade_oltp where cod_prioridade = 4));

insert into estimativa values
(1, (select se.descricao_sequencia_estimativa from sequencia_estimativa_OLTP as se join valor_padrao_sequencia_OLTP as vp on se.cod_sequencia_estimativa = vp.cod_sequencia_estimativa where se.cod_sequencia_estimativa = (select cod_sequencia_estimativa from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 0) limit 1), (select unidade_medida from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 0), (select valor from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 0)),
(2, (select se.descricao_sequencia_estimativa from sequencia_estimativa_OLTP as se join valor_padrao_sequencia_OLTP as vp on se.cod_sequencia_estimativa = vp.cod_sequencia_estimativa where se.cod_sequencia_estimativa = (select cod_sequencia_estimativa from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 1) limit 1), (select unidade_medida from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 1), (select valor from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 1)),
(3, (select se.descricao_sequencia_estimativa from sequencia_estimativa_OLTP as se join valor_padrao_sequencia_OLTP as vp on se.cod_sequencia_estimativa = vp.cod_sequencia_estimativa where se.cod_sequencia_estimativa = (select cod_sequencia_estimativa from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 2) limit 1), (select unidade_medida from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 2), (select valor from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 2)),
(4, (select se.descricao_sequencia_estimativa from sequencia_estimativa_OLTP as se join valor_padrao_sequencia_OLTP as vp on se.cod_sequencia_estimativa = vp.cod_sequencia_estimativa where se.cod_sequencia_estimativa = (select cod_sequencia_estimativa from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 3) limit 1), (select unidade_medida from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 3), (select valor from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 3)),
(5, (select se.descricao_sequencia_estimativa from sequencia_estimativa_OLTP as se join valor_padrao_sequencia_OLTP as vp on se.cod_sequencia_estimativa = vp.cod_sequencia_estimativa where se.cod_sequencia_estimativa = (select cod_sequencia_estimativa from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 4) limit 1), (select unidade_medida from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 4), (select valor from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 4)),
(6, (select se.descricao_sequencia_estimativa from sequencia_estimativa_OLTP as se join valor_padrao_sequencia_OLTP as vp on se.cod_sequencia_estimativa = vp.cod_sequencia_estimativa where se.cod_sequencia_estimativa = (select cod_sequencia_estimativa from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 5) limit 1), (select unidade_medida from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 5), (select valor from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 5)),
(7, (select se.descricao_sequencia_estimativa from sequencia_estimativa_OLTP as se join valor_padrao_sequencia_OLTP as vp on se.cod_sequencia_estimativa = vp.cod_sequencia_estimativa where se.cod_sequencia_estimativa = (select cod_sequencia_estimativa from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 6) limit 1), (select unidade_medida from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 6), (select valor from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 6)),
(8, (select se.descricao_sequencia_estimativa from sequencia_estimativa_OLTP as se join valor_padrao_sequencia_OLTP as vp on se.cod_sequencia_estimativa = vp.cod_sequencia_estimativa where se.cod_sequencia_estimativa = (select cod_sequencia_estimativa from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 7) limit 1), (select unidade_medida from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 7), (select valor from valor_padrao_sequencia_OLTP order by 1 limit 1 offset 7));

insert into responsavel values
(1, (select nome from programador_OLTP where cod_programador = 1), (select data_entrada_projeto from programador_OLTP where cod_programador = 1), (select ne.descricao_nivel_experiencia from nivel_experiencia_OLTP as ne join programador_OLTP as pr on ne.cod_nivel_experiencia = pr.cod_nivel_experiencia where cod_programador = 1)),
(2, (select nome from programador_OLTP where cod_programador = 2), (select data_entrada_projeto from programador_OLTP where cod_programador = 2), (select ne.descricao_nivel_experiencia from nivel_experiencia_OLTP as ne join programador_OLTP as pr on ne.cod_nivel_experiencia = pr.cod_nivel_experiencia where cod_programador = 2)),
(3, (select nome from programador_OLTP where cod_programador = 3), (select data_entrada_projeto from programador_OLTP where cod_programador = 3), (select ne.descricao_nivel_experiencia from nivel_experiencia_OLTP as ne join programador_OLTP as pr on ne.cod_nivel_experiencia = pr.cod_nivel_experiencia where cod_programador = 3)),
(4, (select nome from programador_OLTP where cod_programador = 4), (select data_entrada_projeto from programador_OLTP where cod_programador = 4), (select ne.descricao_nivel_experiencia from nivel_experiencia_OLTP as ne join programador_OLTP as pr on ne.cod_nivel_experiencia = pr.cod_nivel_experiencia where cod_programador = 4)),
(5, (select nome from programador_OLTP where cod_programador = 5), (select data_entrada_projeto from programador_OLTP where cod_programador = 5), (select ne.descricao_nivel_experiencia from nivel_experiencia_OLTP as ne join programador_OLTP as pr on ne.cod_nivel_experiencia = pr.cod_nivel_experiencia where cod_programador = 5)),
(6, (select nome from programador_OLTP where cod_programador = 6), (select data_entrada_projeto from programador_OLTP where cod_programador = 6), (select ne.descricao_nivel_experiencia from nivel_experiencia_OLTP as ne join programador_OLTP as pr on ne.cod_nivel_experiencia = pr.cod_nivel_experiencia where cod_programador = 6)),
(7, (select nome from programador_OLTP where cod_programador = 7), (select data_entrada_projeto from programador_OLTP where cod_programador = 7), (select ne.descricao_nivel_experiencia from nivel_experiencia_OLTP as ne join programador_OLTP as pr on ne.cod_nivel_experiencia = pr.cod_nivel_experiencia where cod_programador = 7)),
(8, (select nome from programador_OLTP where cod_programador = 8), (select data_entrada_projeto from programador_OLTP where cod_programador = 8), (select ne.descricao_nivel_experiencia from nivel_experiencia_OLTP as ne join programador_OLTP as pr on ne.cod_nivel_experiencia = pr.cod_nivel_experiencia where cod_programador = 8)),
(9, (select nome from programador_OLTP where cod_programador = 9), (select data_entrada_projeto from programador_OLTP where cod_programador = 9), (select ne.descricao_nivel_experiencia from nivel_experiencia_OLTP as ne join programador_OLTP as pr on ne.cod_nivel_experiencia = pr.cod_nivel_experiencia where cod_programador = 9)),
(10, (select nome from programador_OLTP where cod_programador = 10), (select data_entrada_projeto from programador_OLTP where cod_programador = 10), (select ne.descricao_nivel_experiencia from nivel_experiencia_OLTP as ne join programador_OLTP as pr on ne.cod_nivel_experiencia = pr.cod_nivel_experiencia where cod_programador = 10)),
(11, (select nome from programador_OLTP where cod_programador = 11), (select data_entrada_projeto from programador_OLTP where cod_programador = 11), (select ne.descricao_nivel_experiencia from nivel_experiencia_OLTP as ne join programador_OLTP as pr on ne.cod_nivel_experiencia = pr.cod_nivel_experiencia where cod_programador = 11)),
(12, (select nome from programador_OLTP where cod_programador = 12), (select data_entrada_projeto from programador_OLTP where cod_programador = 12), (select ne.descricao_nivel_experiencia from nivel_experiencia_OLTP as ne join programador_OLTP as pr on ne.cod_nivel_experiencia = pr.cod_nivel_experiencia where cod_programador = 12));

insert into aplicacao values
(1, (select pr.nome_produto from produto_OLTP as pr join produto_modulo_OLTP as pm on pr.cod_produto = pm.cod_produto where pr.cod_produto = (select cod_produto from produto_modulo_OLTP order by 1 limit 1 offset 0) limit 1), (select md.descricao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 0) limit 1), (select cm.descricao_classificacao_modulo from classificacao_modulo_OLTP as cm join modulo_OLTP as md on cm.cod_classificacao_modulo = md.cod_classificacao_modulo join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where cm.cod_classificacao_modulo = (select md.cod_classificacao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 0) limit 1) limit 1)),
(2, (select pr.nome_produto from produto_OLTP as pr join produto_modulo_OLTP as pm on pr.cod_produto = pm.cod_produto where pr.cod_produto = (select cod_produto from produto_modulo_OLTP order by 1 limit 1 offset 1) limit 1), (select md.descricao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 1) limit 1), (select cm.descricao_classificacao_modulo from classificacao_modulo_OLTP as cm join modulo_OLTP as md on cm.cod_classificacao_modulo = md.cod_classificacao_modulo join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where cm.cod_classificacao_modulo = (select md.cod_classificacao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 1) limit 1) limit 1)),
(3, (select pr.nome_produto from produto_OLTP as pr join produto_modulo_OLTP as pm on pr.cod_produto = pm.cod_produto where pr.cod_produto = (select cod_produto from produto_modulo_OLTP order by 1 limit 1 offset 2) limit 1), (select md.descricao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 2) limit 1), (select cm.descricao_classificacao_modulo from classificacao_modulo_OLTP as cm join modulo_OLTP as md on cm.cod_classificacao_modulo = md.cod_classificacao_modulo join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where cm.cod_classificacao_modulo = (select md.cod_classificacao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 2) limit 1) limit 1)),
(4, (select pr.nome_produto from produto_OLTP as pr join produto_modulo_OLTP as pm on pr.cod_produto = pm.cod_produto where pr.cod_produto = (select cod_produto from produto_modulo_OLTP order by 1 limit 1 offset 3) limit 1), (select md.descricao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 3) limit 1), (select cm.descricao_classificacao_modulo from classificacao_modulo_OLTP as cm join modulo_OLTP as md on cm.cod_classificacao_modulo = md.cod_classificacao_modulo join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where cm.cod_classificacao_modulo = (select md.cod_classificacao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 3) limit 1) limit 1)),
(5, (select pr.nome_produto from produto_OLTP as pr join produto_modulo_OLTP as pm on pr.cod_produto = pm.cod_produto where pr.cod_produto = (select cod_produto from produto_modulo_OLTP order by 1 limit 1 offset 4) limit 1), (select md.descricao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 4) limit 1), (select cm.descricao_classificacao_modulo from classificacao_modulo_OLTP as cm join modulo_OLTP as md on cm.cod_classificacao_modulo = md.cod_classificacao_modulo join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where cm.cod_classificacao_modulo = (select md.cod_classificacao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 4) limit 1) limit 1)),
(6, (select pr.nome_produto from produto_OLTP as pr join produto_modulo_OLTP as pm on pr.cod_produto = pm.cod_produto where pr.cod_produto = (select cod_produto from produto_modulo_OLTP order by 1 limit 1 offset 5) limit 1), (select md.descricao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 5) limit 1), (select cm.descricao_classificacao_modulo from classificacao_modulo_OLTP as cm join modulo_OLTP as md on cm.cod_classificacao_modulo = md.cod_classificacao_modulo join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where cm.cod_classificacao_modulo = (select md.cod_classificacao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 5) limit 1) limit 1)),
(7, (select pr.nome_produto from produto_OLTP as pr join produto_modulo_OLTP as pm on pr.cod_produto = pm.cod_produto where pr.cod_produto = (select cod_produto from produto_modulo_OLTP order by 1 limit 1 offset 6) limit 1), (select md.descricao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 6) limit 1), (select cm.descricao_classificacao_modulo from classificacao_modulo_OLTP as cm join modulo_OLTP as md on cm.cod_classificacao_modulo = md.cod_classificacao_modulo join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where cm.cod_classificacao_modulo = (select md.cod_classificacao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 6) limit 1) limit 1)),
(8, (select pr.nome_produto from produto_OLTP as pr join produto_modulo_OLTP as pm on pr.cod_produto = pm.cod_produto where pr.cod_produto = (select cod_produto from produto_modulo_OLTP order by 1 limit 1 offset 7) limit 1), (select md.descricao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 7) limit 1), (select cm.descricao_classificacao_modulo from classificacao_modulo_OLTP as cm join modulo_OLTP as md on cm.cod_classificacao_modulo = md.cod_classificacao_modulo join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where cm.cod_classificacao_modulo = (select md.cod_classificacao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 7) limit 1) limit 1)),
(9, (select pr.nome_produto from produto_OLTP as pr join produto_modulo_OLTP as pm on pr.cod_produto = pm.cod_produto where pr.cod_produto = (select cod_produto from produto_modulo_OLTP order by 1 limit 1 offset 8) limit 1), (select md.descricao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 8) limit 1), (select cm.descricao_classificacao_modulo from classificacao_modulo_OLTP as cm join modulo_OLTP as md on cm.cod_classificacao_modulo = md.cod_classificacao_modulo join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where cm.cod_classificacao_modulo = (select md.cod_classificacao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 8) limit 1) limit 1)),
(10, (select pr.nome_produto from produto_OLTP as pr join produto_modulo_OLTP as pm on pr.cod_produto = pm.cod_produto where pr.cod_produto = (select cod_produto from produto_modulo_OLTP order by 1 limit 1 offset 9) limit 1), (select md.descricao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 9) limit 1), (select cm.descricao_classificacao_modulo from classificacao_modulo_OLTP as cm join modulo_OLTP as md on cm.cod_classificacao_modulo = md.cod_classificacao_modulo join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where cm.cod_classificacao_modulo = (select md.cod_classificacao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 9) limit 1) limit 1)),
(11, (select pr.nome_produto from produto_OLTP as pr join produto_modulo_OLTP as pm on pr.cod_produto = pm.cod_produto where pr.cod_produto = (select cod_produto from produto_modulo_OLTP order by 1 limit 1 offset 10) limit 1), (select md.descricao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 10) limit 1), (select cm.descricao_classificacao_modulo from classificacao_modulo_OLTP as cm join modulo_OLTP as md on cm.cod_classificacao_modulo = md.cod_classificacao_modulo join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where cm.cod_classificacao_modulo = (select md.cod_classificacao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 10) limit 1) limit 1)),
(12, (select pr.nome_produto from produto_OLTP as pr join produto_modulo_OLTP as pm on pr.cod_produto = pm.cod_produto where pr.cod_produto = (select cod_produto from produto_modulo_OLTP order by 1 limit 1 offset 11) limit 1), (select md.descricao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 11) limit 1), (select cm.descricao_classificacao_modulo from classificacao_modulo_OLTP as cm join modulo_OLTP as md on cm.cod_classificacao_modulo = md.cod_classificacao_modulo join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where cm.cod_classificacao_modulo = (select md.cod_classificacao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 11) limit 1) limit 1)),
(13, (select pr.nome_produto from produto_OLTP as pr join produto_modulo_OLTP as pm on pr.cod_produto = pm.cod_produto where pr.cod_produto = (select cod_produto from produto_modulo_OLTP order by 1 limit 1 offset 12) limit 1), (select md.descricao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 12) limit 1), (select cm.descricao_classificacao_modulo from classificacao_modulo_OLTP as cm join modulo_OLTP as md on cm.cod_classificacao_modulo = md.cod_classificacao_modulo join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where cm.cod_classificacao_modulo = (select md.cod_classificacao_modulo from modulo_OLTP as md join produto_modulo_OLTP as pm on md.cod_modulo = pm.cod_modulo where md.cod_modulo = (select cod_modulo from produto_modulo_OLTP order by 1 limit 1 offset 12) limit 1) limit 1));

insert into tempo values
(1, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 0), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 0), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 0)),
(2, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 1), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 1), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 1)),
(3, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 2), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 2), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 2)),
(4, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 3), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 3), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 3)),
(5, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 4), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 4), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 4)),
(6, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 5), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 5), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 5)),
(7, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 6), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 6), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 6)),
(8, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 7), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 7), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 7)),
(9, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 8), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 8), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 8)),
(10, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 9), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 9), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 9)),
(11, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 10), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 10), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 10)),
(12, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 11), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 11), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 11)),
(13, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 12), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 12), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 12)),
(14, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 13), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 13), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 13)),
(15, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 14), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 14), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 14)),
(16, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 15), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 15), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 15)),
(17, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 16), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 16), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 16)),
(18, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 17), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 17), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 17)),
(19, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 18), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 18), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 18)),
(20, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 19), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 19), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 19)),
(21, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 20), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 20), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 20)),
(22, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 21), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 21), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 21)),
(23, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 22), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 22), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 22)),
(24, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 23), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 23), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 23)),
(25, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 24), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 24), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 24)),
(26, (select quinzena from sprint_OLTP order by ano, mes, quinzena limit 1 offset 25), (select mes from sprint_OLTP order by ano, mes, quinzena limit 1 offset 25), (select ano from sprint_OLTP order by ano, mes, quinzena limit 1 offset 25));